<?php
	include_once('config/config.php');
?>
<!DOCTYPE html>
<html> 
<head> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/css/estilos.css">
	<link rel="stylesheet" href="<?=BASE_URL?>/js/alertifyjs/css/alertify.css">
    <title>Rutas</title> 
    <!--
    <link rel="stylesheet" href="css/flatly.min.css">
    -->
	
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyC4juB_QGsiWC5yhcibv9V8n_FRlOMupsA"></script>
	<script type="text/javascript" src="<?=BASE_URL?>/js/jquery.js"></script> 
	
    <script type="text/javascript" src="<?=BASE_URL?>/js/functions.js"></script>  

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	
	
	<script src="<?=BASE_URL?>/js/alertifyjs/alertify.js"></script>
	
</head> 
<body class="container">

	
	
	<h2>Generador de rutas</h2>

    <div class="container">
		
		<div class="form-inline row col-md-12">			
			<select class="form-control" id="primero">
				<option value="0">Primer punto </option>
				<?=$mapas->get_ciudades();?>
			</select> &nbsp;
			<select class="form-control" id="segundo">
				<option value="0">Segundo punto </option>
				<?=$mapas->get_ciudades();?>
			</select> &nbsp;
			<select class="form-control" id="tercero">
				<option value="0">Tercer punto </option>
				<?=$mapas->get_ciudades();?>
			</select> &nbsp;
			<div class="form-group">
				<input class="btn btn-primary" type="submit" value="Graficar Ruta" onclick="graficar();setTimeout('recargaTabla()',1000);">
			</div>
		</div>
		<br>
		<div class="row col-md-12">
			<hr>
		</div>
		<div id="rutas" class="row col-md-12">
			<div id="tabla"></div>
		</div>
	</div>
	
	<div id="map" class="row col-md-12" style="width:100%;height:400px;" allowfullscreen></div>
	<!-- Modal para edición de registros -->
	<div class="modal fade" id="modalEdicion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div id="actualiza"></div>
		</div>
	
	
<!--
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
-->
</body>
</html>